### ISSUE TITLE
Strings Module and repl questions

### ISSUE THREAD

**Issue by rascala** [kjnilsson/fez#4] opened 2017-06-16 09:28 UTC
Hi Karl,

I have been adding some more wrappers to the String library.
Plan start working on some basic regex after that.
I have some experience with elixir and not much with erlang, but so far so good.

Have you had any thoughts about a repl with code-loading and inspection?
Connecting to a running process would imply marshalling/unmarshalling erlang data.
I think type-providers would probably work very well there(especially with remote processes)

**Comment by kjnilsson** [comment] 2017-06-16 09:38
Hi, that's fantastic! The standard libraries are excellent places for people to contribute as there is a lot to cover and I'm focussing on the core compiler. Feel free to submit a PR whenever and I can check you are on the right track and so on. 

Re: repl. Fez is very much an fsharp -> core erlang translator so a repl where you typed in fsharp expressions that got translated then evaluated could be possible. The output would be erlang however but I can see that being useful. The compiler is slow to run so having a more interactive environment would be good for productivity.

**Comment by rascala** [comment] 2017-06-16 12:02
Hi Karl,

Ran into some issues with literal chars not being implemented.
I added it looking at the string implementations and removed the trailing single-quote in cerl.fs for chars.

But I have no clue if I broke anything.
Were you planning to do anything special with char implementations?

-- Siddarth

**Comment by kjnilsson** [comment] 2017-06-16 12:35
no that is probably just an omission because I haven't tested it. if `run-tests.sh` passes there shouldn't be any obvious regressions.

**Comment by kjnilsson** [comment] 2017-06-16 19:37
Ok this has been merged. Thanks very much. :)

**Closed** 2017-06-17 06:41 UTC
